// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA50AGAESWozAKN5XzYJ7G6sd_3G1tE2bA',
    appId: '1:612794064156:web:b8c5f97ee7a3c05d7f6ed9',
    messagingSenderId: '612794064156',
    projectId: 'omuited',
    authDomain: 'omuited.firebaseapp.com',
    storageBucket: 'omuited.appspot.com',
    measurementId: 'G-ZW6MPYSP2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-eOfucwHZZtN_v8hQfxsvQ3d1shH6tY',
    appId: '1:612794064156:android:273865845a11a8567f6ed9',
    messagingSenderId: '612794064156',
    projectId: 'omuited',
    storageBucket: 'omuited.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhAxPiSqXlWVsBDCDFY5EshtiQZ6_yQ_k',
    appId: '1:612794064156:ios:7042cfbf5cbd957f7f6ed9',
    messagingSenderId: '612794064156',
    projectId: 'omuited',
    storageBucket: 'omuited.appspot.com',
    iosClientId: '612794064156-krje52ig6ih4mfk09j18c8ef2d7lt352.apps.googleusercontent.com',
    iosBundleId: 'com.saleh.omUnited',
  );
}
